version: '3.1'
services:
  stats-server:
      build:
        context: ./ewm-stat-service/stat-service
        dockerfile: Dockerfile
      image: ewm-stat-service
      container_name: ewm-stat-service
      ports:
        - "9090:9090"
      depends_on:
        - stats-db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stat-postgres
    ports:
      - "6541:5432"
    environment:
      - TZ=GMT
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - ewm-db
    environment:
      - EWM_STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-postgres
    ports:
      - "6545:5432"
    environment:
      - TZ=GMT
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
